# Generated by Django 5.0.14 on 2025-10-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_post_category_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="reply",
            field=models.TextField(blank=True, null=True),
        ),
    ]
