# Generated by Django 5.0.14 on 2025-10-24 12:53

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_remove_comment_reply_comment_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=smart_selects.db_fields.ChainedForeignKey(
                blank=True,
                chained_field="post",
                chained_model_field="post",
                limit_choices_to={"parent__isnull": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="blog.comment",
            ),
        ),
    ]
