# Generated by Django 5.0.14 on 2025-10-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_comment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_locked",
            field=models.BooleanField(default=False, help_text="是否僅限訂閱者閱讀"),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, max_length=120, unique=True
            ),
        ),
    ]
