# Generated by Django 5.0.14 on 2025-11-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_post_is_locked_alter_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
