# Generated by Django 5.0.14 on 2025-11-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nowpayment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nowpaymentsubscription",
            name="raw",
            field=models.JSONField(default=dict),
        ),
    ]
